<?php
$config['rewrite_url_userindex']='/my/';
$config['rewrite_url_userprofile']='/my/profile.html';
$config['rewrite_url_userpwd']='/my/change_pwd.html';
$config['rewrite_url_useravatar']='/my/picture.html';
$config['rewrite_url_userupgrade']='/my/upgrade.html';
$config['rewrite_url_userpms']='/my/message.html';
$config['rewrite_url_userplayrecord']='/my/playrecord.html';
$config['rewrite_url_userexchange']='/my/exchange.html';
$config['rewrite_url_payment']='/payment/';
$config['rewrite_url_regist']='/regist.html';
$config['rewrite_url_login']='/login.html';
$config['rewrite_url_logout']='/logout.html';
$config['rewrite_url_signin']='/signin.html';
$config['rewrite_url_forget']='/forget.html';
$config['rewrite_url_servicequestion']='/service/question.html';
$config['rewrite_url_serviceindex']='/service/';
$config['rewrite_url_servicequery']='/service/query.html';
$config['rewrite_url_servicefaq']='/service/searchfaq.html';
$config['rewrite_url_payindex']='/payment/';
$config['rewrite_url_swi_points']='/payment/swi_points';
$config['rewrite_url_pay_record']='/payment/pay_record';
$config['rewrite_url_swi_record']='/payment/swi_record';
$config['rewrite_url_playrecorde']='/my/playrecord.html';
$config['rewrite_url_card']='/card.html';
?>